spring:

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/dms
#    username: ${DB_USERNAME:ming}
#    password: ${DB_PASSWORD:530227177}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dms?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:530227177}



  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1GB

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    protocol: smtp
    username: ${MAIL_USERNAME:19959771806@163.com}
    password: ${MAIL_PASSWORD:GHHYJYLPXOQIHKRW}
    nickname: yuban #    发件名称
    properties:
      mail:
        smtp:
        auth: true #启用SMTP服务器的身份验证，这是为了确保只有合法用户可以发送邮件。
        ssl: true
        starttls:
          enable: #启用TLS加密，这是为了确保邮件传输的安全性。
          required: false #要求使用TLS加密，如果连接不是通过TLS加密传输，则连接将失败。
      debug: true

  data:
    redis:
      host: localhost
      port: 6379




server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    useGeneratedKeys: true
    default-scripting-language-driver: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver

logging:
  level:
    com:
      yuban:
        shop:
          service: info
          mapper: debug
          controller: info
    com.baomidou: DEBUG
    org.mybatis: DEBUG

#上传路径
upload:
  path: ${user.dir}\yubanSever\datas

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  show-actuator: true